### PR TITLE
Update of FRENCH translation for Post Love extension

### PR DESCRIPTION
**Pull request by Galixte**
Update for 1.1.0 version.

### CODE REVIEW

**Comment by Galixte** [comment]
Hi @satanasov,

if your development is accomplished for language keys, this PR is up to date for FRENCH language.

**Comment by Galixte** [comment]
Hi @satanasov,

could you merge this, please ?

**Comment by satanasov** [comment]
Please rebase it against master ...

**Comment by Galixte** [comment]
Done here: https://github.com/satanasov/postlove/pull/18.

**Pull request closed without merging**
